#include "energyFunctions.h"

// Defined in
// A Variational Model for Reconstructive Phase Transformations in Crystals,
// and their Relation to Dislocations and Plasticity
// Sergio Conti & Giovanni Zanzotto

// Generated by python script
namespace ContiPotential {

double energyDensity(double C11, double C22, double C12, double beta, double K,
                     double noise) {
  double x0 = C11 * C22 - pow(C12, 2);
  double x1 = noise * x0;
  double x2 = pow(x0, -1.0 / 2.0);
  double x3 = C11 * x2;
  double x4 = C22 * x2;
  double x5 = pow(x3 - x4, 2);
  double x6 = C12 * x2;
  double x7 = x3 + x4 - 4 * x6;
  double x8 = 0.25 * x5 + 0.083333333333333329 * pow(x7, 2);
  double x9 = pow(x8, 3);
  double x10 = x5 * x7 - 0.1111111111111111 * pow(x7, 3);
  double x11 = pow(x10, 2);
  double x12 = 0.33333333333333331 * x3 + 0.33333333333333331 * x4 -
               0.33333333333333331 * x6;
  double x13 = x10 * x8;

  double phi = K * (x1 - log(x1)) +
               beta * (0.000946969696969697 * x11 + pow(x12, 4) * x8 +
                       0.035353535353535352 * x13 * (x3 + x4 - x6) -
                       0.4141414141414142 * x9) +
               x10 * pow(x12, 3) + 0.032196969696969696 * x11 -
               0.24242424242424243 * x13 * (x3 + x4 - x6) +
               0.36363636363636365 * x9;

  return phi;
}

Matrix2d stress(double C11, double C22, double C12, double beta, double K,
                double noise) {
  double x0 = C11 * C22;
  double x1 = pow(C12, 2);
  double x2 = x0 - x1;
  double x3 = 1.0 / x2;
  double x4 = pow(x2, -3.0 / 2.0);
  double x5 = pow(C22, 2) * x4;
  double x6 = pow(x2, -1.0 / 2.0);
  double x7 = -1.0 * x6;
  double x8 = x0 * x4;
  double x9 = x7 + 0.5 * x8;
  double x10 = C11 * x6;
  double x11 = C22 * x6;
  double x12 = 4 * x6;
  double x13 = -C12 * x12 + x10 + x11;
  double x14 = x10 - x11;
  double x15 = pow(x14, 2);
  double x16 = -0.1111111111111111 * pow(x13, 3) + x13 * x15;
  double x17 = -0.33333333333333331 * C12 * x6 + 0.33333333333333331 * x10 +
               0.33333333333333331 * x11;
  double x18 = x16 * pow(x17, 2);
  double x19 = 2.6666666666666665 * x6;
  double x20 = -x19;
  double x21 = x20 + 1.3333333333333333 * x8;
  double x22 = pow(x13, 2);
  double x23 = 0.25 * x15 + 0.083333333333333329 * x22;
  double x24 = 0.090909090909090912 * x23;
  double x25 = x16 * x24;
  double x26 = pow(x23, 2);
  double x27 = 2 * x6;
  double x28 = x27 - x8;
  double x29 = x14 * (x28 + x5);
  double x30 = -x27 + x8;
  double x31 = x13 * (4 * C12 * C22 * x4 - x30 - x5);
  double x32 = x26 * (0.75 * x29 + 0.25 * x31);
  double x33 = 0.25 * x29 + 0.083333333333333329 * x31;
  double x34 = x16 * x33;
  double x35 = -C12 * x19 + 2.6666666666666665 * x10 + 2.6666666666666665 * x11;
  double x36 = 0.090909090909090912 * x35;
  double x37 = pow(x17, 3);
  double x38 = 2 * C12;
  double x39 = x38 * x4;
  double x40 = C22 * x39;
  double x41 = -x40;
  double x42 = -x6 + (1.0 / 2.0) * x8;
  double x43 = x15 * (-x41 - x42 - 1.0 / 2.0 * x5);
  double x44 = -3 * x6 + (3.0 / 2.0) * x8;
  double x45 = x22 * (6 * C12 * C22 * x4 - x44 - 3.0 / 2.0 * x5);
  double x46 = x13 * x29;
  double x47 = x43 - 0.1111111111111111 * x45 + x46;
  double x48 = x24 * x35;
  double x49 = x16 * (2 * x43 - 0.22222222222222221 * x45 + 2 * x46);
  double x50 = -1.3333333333333333 * x6;
  double x51 = x50 + 0.66666666666666663 * x8;
  double x52 = x23 * x37;
  double x53 = pow(x17, 4);
  double x54 = 2.333333333333333 * x6;
  double x55 = -x54;
  double x56 = x55 + 1.1666666666666665 * x8;
  double x57 = 0.015151515151515152 * x23;
  double x58 = x16 * x57;
  double x59 = -C12 * x54 + 2.333333333333333 * x10 + 2.333333333333333 * x11;
  double x60 = 0.015151515151515152 * x59;
  double x61 = x57 * x59;
  double x62 = pow(C11, 2) * x4;
  double x63 = x14 * (-x28 - x62);
  double x64 = x13 * (4 * C11 * C12 * x4 - x30 - x62);
  double x65 = x26 * (0.75 * x63 + 0.25 * x64);
  double x66 = 0.25 * x63 + 0.083333333333333329 * x64;
  double x67 = x16 * x66;
  double x68 = x15 * (2 * C11 * C12 * x4 - x42 - 1.0 / 2.0 * x62);
  double x69 = x22 * (6 * C11 * C12 * x4 - x44 - 3.0 / 2.0 * x62);
  double x70 = x13 * x63;
  double x71 = x68 - 0.1111111111111111 * x69 + x70;
  double x72 = x16 * (2 * x68 - 0.22222222222222221 * x69 + 2 * x70);
  double x73 = C12 * x4;
  double x74 = C11 * x73;
  double x75 = C22 * x73;
  double x76 = x1 * x4;
  double x77 = C11 * x39;
  double x78 = x14 * (x41 + x77);
  double x79 = x13 * (x40 - 8 * x6 - 8 * x76 + x77);
  double x80 = x26 * (0.75 * x78 + 0.25 * x79);
  double x81 = 0.25 * x78 + 0.083333333333333329 * x79;
  double x82 = x16 * x81;
  double x83 = x15 * (-x12 + x74 + x75 - 4 * x76);
  double x84 = x13 * x78;
  double x85 = x22 * (-12 * x6 + 3 * x74 + 3 * x75 - 12 * x76);
  double x86 = x83 + x84 - 0.1111111111111111 * x85;
  double x87 = x16 * (2 * x83 + 2 * x84 - 0.22222222222222221 * x85);

  double dPhi_dC11 = C22 * K * (noise - x3) +
                     beta * (-0.4141414141414142 * x32 + x33 * x53 + x34 * x60 +
                             x47 * x61 + 0.000946969696969697 * x49 -
                             x52 * (-0.66666666666666663 * C12 * C22 * x4 +
                                    0.66666666666666663 * x5 + x51) -
                             x58 * (-1.1666666666666665 * C12 * C22 * x4 +
                                    1.1666666666666665 * x5 + x56)) -
                     x18 * (-0.5 * C12 * C22 * x4 + 0.5 * x5 + x9) +
                     x25 * (-1.3333333333333333 * C12 * C22 * x4 + x21 +
                            1.3333333333333333 * x5) +
                     0.36363636363636365 * x32 - x34 * x36 + x37 * x47 -
                     x47 * x48 + 0.032196969696969696 * x49;
  double dPhi_dC22 = C11 * K * (noise - x3) +
                     beta * (-x52 * (-0.66666666666666663 * C11 * C12 * x4 +
                                     x51 + 0.66666666666666663 * x62) +
                             x53 * x66 -
                             x58 * (-1.1666666666666665 * C11 * C12 * x4 + x56 +
                                    1.1666666666666665 * x62) +
                             x60 * x67 + x61 * x71 - 0.4141414141414142 * x65 +
                             0.000946969696969697 * x72) -
                     x18 * (-0.5 * C11 * C12 * x4 + 0.5 * x62 + x9) +
                     x25 * (-1.3333333333333333 * C11 * C12 * x4 + x21 +
                            1.3333333333333333 * x62) -
                     x36 * x67 + x37 * x71 - x48 * x71 +
                     0.36363636363636365 * x65 + 0.032196969696969696 * x72;
  double dPhi_dC12 =
      K * (2 * C12 * x3 - noise * x38) +
      beta * (x52 * (x50 + 1.3333333333333333 * x74 + 1.3333333333333333 * x75 -
                     1.3333333333333333 * x76) +
              x53 * x81 +
              x58 * (x55 + 2.333333333333333 * x74 + 2.333333333333333 * x75 -
                     2.333333333333333 * x76) +
              x60 * x82 + x61 * x86 - 0.4141414141414142 * x80 +
              0.000946969696969697 * x87) +
      x18 * (x7 + 1.0 * x74 + 1.0 * x75 - 1.0 * x76) -
      x25 * (x20 + 2.6666666666666665 * x74 + 2.6666666666666665 * x75 -
             2.6666666666666665 * x76) -
      x36 * x82 + x37 * x86 - x48 * x86 + 0.36363636363636365 * x80 +
      0.032196969696969696 * x87;

  return Matrix2d{{dPhi_dC11, dPhi_dC12 / 2}, {dPhi_dC12 / 2, dPhi_dC22}};
}

double energyDensityAndStress(double C11, double C22, double C12, double beta,
                              double K, double noise, Matrix2d *stress_out) {
  double x0 = C11 * C22;
  double x1 = pow(C12, 2);
  double x2 = x0 - x1;
  double x3 = noise * x2;
  double x4 = pow(x2, -1.0 / 2.0);
  double x5 = C11 * x4;
  double x6 = C22 * x4;
  double x7 = x5 - x6;
  double x8 = pow(x7, 2);
  double x9 = 4 * x4;
  double x10 = -C12 * x9 + x5 + x6;
  double x11 = pow(x10, 2);
  double x12 = 0.083333333333333329 * x11 + 0.25 * x8;
  double x13 = pow(x12, 3);
  double x14 = -0.1111111111111111 * pow(x10, 3) + x10 * x8;
  double x15 = pow(x14, 2);
  double x16 = -0.33333333333333331 * C12 * x4 + 0.33333333333333331 * x5 +
               0.33333333333333331 * x6;
  double x17 = pow(x16, 3);
  double x18 = 2.6666666666666665 * x4;
  double x19 = -C12 * x18 + 2.6666666666666665 * x5 + 2.6666666666666665 * x6;
  double x20 = x12 * x14;
  double x21 = 0.090909090909090912 * x20;
  double x22 = pow(x16, 4);
  double x23 = 2.333333333333333 * x4;
  double x24 = -C12 * x23 + 2.333333333333333 * x5 + 2.333333333333333 * x6;
  double x25 = 0.015151515151515152 * x20;
  double x26 = 1.0 / x2;
  double x27 = pow(x2, -3.0 / 2.0);
  double x28 = pow(C22, 2) * x27;
  double x29 = -1.0 * x4;
  double x30 = x0 * x27;
  double x31 = x29 + 0.5 * x30;
  double x32 = x14 * pow(x16, 2);
  double x33 = -x18;
  double x34 = 1.3333333333333333 * x30 + x33;
  double x35 = pow(x12, 2);
  double x36 = 2 * x4;
  double x37 = -x30 + x36;
  double x38 = x7 * (x28 + x37);
  double x39 = x30 - x36;
  double x40 = x10 * (4 * C12 * C22 * x27 - x28 - x39);
  double x41 = x35 * (0.75 * x38 + 0.25 * x40);
  double x42 = 0.25 * x38 + 0.083333333333333329 * x40;
  double x43 = x14 * x42;
  double x44 = 0.090909090909090912 * x19;
  double x45 = 2 * C12;
  double x46 = x27 * x45;
  double x47 = C22 * x46;
  double x48 = -x47;
  double x49 = (1.0 / 2.0) * x30 - x4;
  double x50 = x8 * (-1.0 / 2.0 * x28 - x48 - x49);
  double x51 = (3.0 / 2.0) * x30 - 3 * x4;
  double x52 = x11 * (6 * C12 * C22 * x27 - 3.0 / 2.0 * x28 - x51);
  double x53 = x10 * x38;
  double x54 = x50 - 0.1111111111111111 * x52 + x53;
  double x55 = x12 * x54;
  double x56 = x14 * (2 * x50 - 0.22222222222222221 * x52 + 2 * x53);
  double x57 = -1.3333333333333333 * x4;
  double x58 = 0.66666666666666663 * x30 + x57;
  double x59 = x12 * x17;
  double x60 = -x23;
  double x61 = 1.1666666666666665 * x30 + x60;
  double x62 = 0.015151515151515152 * x24;
  double x63 = pow(C11, 2) * x27;
  double x64 = x7 * (-x37 - x63);
  double x65 = x10 * (4 * C11 * C12 * x27 - x39 - x63);
  double x66 = x35 * (0.75 * x64 + 0.25 * x65);
  double x67 = 0.25 * x64 + 0.083333333333333329 * x65;
  double x68 = x14 * x67;
  double x69 = x8 * (2 * C11 * C12 * x27 - x49 - 1.0 / 2.0 * x63);
  double x70 = x11 * (6 * C11 * C12 * x27 - x51 - 3.0 / 2.0 * x63);
  double x71 = x10 * x64;
  double x72 = x69 - 0.1111111111111111 * x70 + x71;
  double x73 = x12 * x72;
  double x74 = x14 * (2 * x69 - 0.22222222222222221 * x70 + 2 * x71);
  double x75 = C12 * x27;
  double x76 = C11 * x75;
  double x77 = C22 * x75;
  double x78 = x1 * x27;
  double x79 = C11 * x46;
  double x80 = x7 * (x48 + x79);
  double x81 = x10 * (-8 * x4 + x47 - 8 * x78 + x79);
  double x82 = x35 * (0.75 * x80 + 0.25 * x81);
  double x83 = 0.25 * x80 + 0.083333333333333329 * x81;
  double x84 = x14 * x83;
  double x85 = x8 * (x76 + x77 - 4 * x78 - x9);
  double x86 = x10 * x80;
  double x87 = x11 * (-12 * x4 + 3 * x76 + 3 * x77 - 12 * x78);
  double x88 = x85 + x86 - 0.1111111111111111 * x87;
  double x89 = x12 * x88;
  double x90 = x14 * (2 * x85 + 2 * x86 - 0.22222222222222221 * x87);

  double phi = K * (x3 - log(x3)) +
               beta * (x12 * x22 - 0.4141414141414142 * x13 +
                       0.000946969696969697 * x15 + x24 * x25) +
               0.36363636363636365 * x13 + x14 * x17 +
               0.032196969696969696 * x15 - x19 * x21;
  double dPhi_dC11 = C22 * K * (noise - x26) +
                     beta * (x22 * x42 -
                             x25 * (-1.1666666666666665 * C12 * C22 * x27 +
                                    1.1666666666666665 * x28 + x61) -
                             0.4141414141414142 * x41 + x43 * x62 + x55 * x62 +
                             0.000946969696969697 * x56 -
                             x59 * (-0.66666666666666663 * C12 * C22 * x27 +
                                    0.66666666666666663 * x28 + x58)) +
                     x17 * x54 +
                     x21 * (-1.3333333333333333 * C12 * C22 * x27 +
                            1.3333333333333333 * x28 + x34) -
                     x32 * (-0.5 * C12 * C22 * x27 + 0.5 * x28 + x31) +
                     0.36363636363636365 * x41 - x43 * x44 - x44 * x55 +
                     0.032196969696969696 * x56;
  double dPhi_dC22 = C11 * K * (noise - x26) +
                     beta * (x22 * x67 -
                             x25 * (-1.1666666666666665 * C11 * C12 * x27 +
                                    x61 + 1.1666666666666665 * x63) -
                             x59 * (-0.66666666666666663 * C11 * C12 * x27 +
                                    x58 + 0.66666666666666663 * x63) +
                             x62 * x68 + x62 * x73 - 0.4141414141414142 * x66 +
                             0.000946969696969697 * x74) +
                     x17 * x72 +
                     x21 * (-1.3333333333333333 * C11 * C12 * x27 + x34 +
                            1.3333333333333333 * x63) -
                     x32 * (-0.5 * C11 * C12 * x27 + x31 + 0.5 * x63) -
                     x44 * x68 - x44 * x73 + 0.36363636363636365 * x66 +
                     0.032196969696969696 * x74;
  double dPhi_dC12 =
      K * (2 * C12 * x26 - noise * x45) +
      beta * (x22 * x83 +
              x25 * (x60 + 2.333333333333333 * x76 + 2.333333333333333 * x77 -
                     2.333333333333333 * x78) +
              x59 * (x57 + 1.3333333333333333 * x76 + 1.3333333333333333 * x77 -
                     1.3333333333333333 * x78) +
              x62 * x84 + x62 * x89 - 0.4141414141414142 * x82 +
              0.000946969696969697 * x90) +
      x17 * x88 -
      x21 * (x33 + 2.6666666666666665 * x76 + 2.6666666666666665 * x77 -
             2.6666666666666665 * x78) +
      x32 * (x29 + 1.0 * x76 + 1.0 * x77 - 1.0 * x78) - x44 * x84 - x44 * x89 +
      0.36363636363636365 * x82 + 0.032196969696969696 * x90;

  *stress_out =
      Matrix2d{{dPhi_dC11, dPhi_dC12 / 2}, {dPhi_dC12 / 2, dPhi_dC22}};

  return phi;
}

} // namespace ContiPotential