name=pgo_50x50
rows=50
cols=50
usingPBC=true
reconnectionMethod=edgeFlip
scenario=simpleShear
nrThreads=2
seed=0
QDSD=0.0
initialGuessNoise=0.05
meshDiagonal=major
energyFunction=contiSquare
bulkModulus=4.0

startLoad=0.14
loadIncrement=1e-5
maxLoad=0.1402

minimizer=LBFGS
epsR=1e-5

LBFGSNrCorrections=10
LBFGSScale=1.0
LBFGSEpsg=1e-20
LBFGSEpsf=1e-20
LBFGSEpsx=1e-20
LBFGSMaxIterations=0

CGScale=1.0
CGEpsg=1e-20
CGEpsf=1e-20
CGEpsx=1e-20
CGMaxIterations=0

finc=1.1
fdec=0.5
alphaStart=0.1
falpha=0.99
dtStart=0.1
dtMax=0.3
dtMin=1e-7
maxCompS=0.01
eps=1e-20
epsRel=0
delta=0
maxIt=100000

logDuringMinimization=false
writeDumps=false
plasticityEventThreshold=0.01
energyDropThreshold=0.001
showProgress=0
