# Simulation settings

# The nodes are arranged in a square. The number of nodes on a side of the square is:
squareNrNodes: 50

# Starting load of the simulation
startLoad: 0.15
# Load increment 
loadIncrement: 0.01
# The simulation stops when we reach this load
maxLoad: 0.7
